version: "3.1"
services:
  redis:
    image: redis:4
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - shoutbox-links
    volumes:
      - redis-data:/shoutbox
  webapp:
    build:
      context: .
    # 设置node启动的环境变量
    environment:
      - NODE_ENV=development
      - REDIS_HOST=$REDIS_HOST
    networks:
      - shoutbox-links
    command: nodemon --inspect=0.0.0.0:9229 ./bin/www
    ports:
      - "$PORT:80"
      - "9229:9229"
    volumes:
      - .:/opt/shoutbox
      - ./package.json:/opt/shoutbox/package.json
      - ./package-lock.json:/opt/shoutbox/package-lock.json
      - /opt/shoutbox/node_modules/bcrypt
      - notused:/shoutbox/node_modules
    depends_on:
      - redis
networks:
  shoutbox-links:
volumes:
  notused:
  redis-data:
